In [37]:
import pandas as pd
import numpy as np

In [3]:
train = pd.read_csv('/content/drive/MyDrive/5001_kaggle/train.csv')
test = pd.read_csv('/content/drive/MyDrive/5001_kaggle/test.csv')
sample = pd.read_csv('/content/drive/MyDrive/5001_kaggle/sample_submission.csv')

In [4]:
train

id  MO HLADR+ MFI (cells/ul)  Neu CD64+MFI (cells/ul)  CD3+T (cells/ul)  \
0    0                    3556.0                   2489.0            265.19   
1    1                    1906.0                    134.0           1442.61   
2    2                    1586.0                     71.0           1332.74   
3    3                     683.0                     94.0            419.23   
4    4                    1032.0                     71.0           1102.72   
..  ..                       ...                      ...               ...   
82  82                     626.0                     68.0           1771.57   
83  83                    1237.0                     71.0           1348.53   
84  84                     634.0                   1002.0           1300.00   
85  85                     112.0                    884.0            942.83   
86  86                     195.0                    213.0            724.00   

    CD8+T (cells/ul)  CD4+T (cells/ul)  NK (cells/ul)  CD19+ (cells/ul)  \
0              77.53            176.55           0.00              4.20   
1             551.90            876.07         112.10            168.15   
2             684.20            655.26         244.95            216.52   
3             255.80            162.17          72.05             44.68   
4             480.27            625.30         188.78            130.77   
..               ...               ...            ...               ...   
82            666.99           1117.48         360.21            118.84   
83            428.09            924.69         120.02             48.67   
84            558.00            724.00          67.00            105.00   
85            378.49            567.06         116.77             31.81   
86            364.00            361.00          18.00            155.00   

    CD45+ (cells/ul)  Age  Sex 0M1F  Mono CD64+MFI (cells/ul)  label  
0             307.91   52         0                    7515.0      1  
1            1735.48   20         1                    1756.0      0  
2            1820.04   28         1                    1311.0      0  
3             538.22   55         1                    1443.0      0  
4            1427.97   28         1                    1542.0      0  
..               ...  ...       ...                       ...    ...  
82           2306.82   42         1                    1521.0      0  
83           1524.78   56         0                    1345.0      0  
84           1484.26   34         0                    2926.0      1  
85           1104.59   33         1                    2352.0      1  
86            897.00   19         1                    2445.0      1  

[87 rows x 13 columns]

In [5]:
test

id  MO HLADR+ MFI (cells/ul)  Neu CD64+MFI (cells/ul)  CD3+T (cells/ul)  \
0    0                    2843.0                    156.0           1358.52   
1    1                     437.0                    137.0            509.43   
2    2                     826.0                     82.0           1232.22   
3    3                     861.0                     50.0           1512.86   
4    4                    1160.0                    157.0            890.42   
5    5                     867.0                     85.0           1662.11   
6    6                    1330.0                    114.0           1307.95   
7    7                     494.0                     48.0           1522.39   
8    8                    2119.0                     73.0           1219.66   
9    9                    2052.0                     39.0           1223.65   
10  10                    4195.0                    134.0           1513.79   
11  11                     819.0                   1000.0            794.33   
12  12                     685.0                     60.0            470.04   
13  13                    1330.0                    114.0           1307.95   
14  14                      82.0                     30.0            693.25   
15  15                     781.0                     43.0           1537.36   
16  16                    2140.0                    125.0           2771.20   
17  17                    1005.0                     93.0           1061.65   
18  18                    1202.0                     39.0            716.76   
19  19                     660.0                     43.0            886.57   
20  20                    1289.0                    272.0            583.00   
21  21                    2238.0                    539.0            850.05   
22  22                     127.0                     81.0            435.00   
23  23                     880.0                     38.0            773.79   
24  24                    3232.0                     72.0           2017.32   
25  25                     902.0                   1141.0            258.01   
26  26                     922.0                    167.0           2122.97   
27  27                    1520.0                     67.0            829.56   
28  28                     313.0                    382.0            632.45   
29  29                    1240.0                     59.0           1071.75   
30  30                    1208.0                    460.0           1492.00   
31  31                     601.0                   1080.0            306.71   
32  32                    1814.0                    143.0            627.33   
33  33                     232.0                    615.0            352.11   
34  34                    1078.0                    238.0            755.15   
35  35                    1085.0                     24.0           1970.56   
36  36                    1851.0                     95.0           1498.79   
37  37                     402.0                    378.0            544.54   
38  38                     909.0                    574.0            326.77   
39  39                    1296.0                    148.0           1328.00   
40  40                    1784.0                    474.0            337.75   
41  41                     676.0                     64.0            622.25   
42  42                     629.0                     76.0            427.06   
43  43                     721.0                    117.0            983.00   
44  44                    1733.0                    134.0           1443.62   
45  45                    1546.0                    184.0            832.08   
46  46                     838.0                    226.0           1025.32   
47  47                     740.0                    187.0            530.77   
48  48                     494.0                     61.0           1568.54   
49  49                    1700.0                     7

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.linear_model import LogisticRegression

In [ ]:
train_X

In [29]:
train.isnull().sum()

id                          0
MO HLADR+ MFI (cells/ul)    1
Neu CD64+MFI (cells/ul)     1
CD3+T (cells/ul)            0
CD8+T (cells/ul)            0
CD4+T (cells/ul)            0
NK (cells/ul)               0
CD19+ (cells/ul)            0
CD45+ (cells/ul)            0
Age                         0
Sex 0M1F                    0
Mono CD64+MFI (cells/ul)    1
label                       0
dtype: int64

In [34]:
def fill_value(df, col_list, fill=0):
    """
    a function to fill missing values
    @param df: dataframe
    @param col_list: list of column names
    @param fill: int (0) or str (mean, mode, median)
    return: preprocessed dataframe
    """
    if type(fill) == int or fill not in ["mean", "median", "mode"]:
        df[col_list] = df[col_list].fillna(fill)
    else:
        if fill == "mean":
            val = df[col_list].mean()
            val_map = val.to_dict()
        elif fill == "median":
            val = df[col_list].median()
            val_map = val.to_dict()
        else:
            val = df[col_list].mode()
            val_map = val.loc[0].to_dict()
        
        print(val_map)
        
        for col in col_list:
            df[col] = df[col].replace(np.nan, val_map[col])
        
    return df

In [35]:
def fill_missing_value(df):   
  columns = df.columns
  df = fill_value(df, columns, fill="median")   
  return df

In [38]:
train = fill_missing_value(train) 

{'id': 43.0, 'MO HLADR+ MFI (cells/ul)': 1108.5, 'Neu CD64+MFI (cells/ul)': 124.5, 'CD3+T (cells/ul)': 871.71, 'CD8+T (cells/ul)': 423.27, 'CD4+T (cells/ul)': 459.72, 'NK (cells/ul)': 188.78, 'CD19+ (cells/ul)': 89.79, 'CD45+ (cells/ul)': 1179.27, 'Age': 41.0, 'Sex 0M1F': 0.0, 'Mono CD64+MFI (cells/ul)': 1757.5, 'label': 0.0}


In [42]:
train_X = train[train.columns[1:-1]]
train_y = train[train.columns[-1]]
test_X = test[train.columns[1:-1]]

In [40]:
random_model = RandomForestClassifier()
random_model.fit(train_X, train_y)
random_y_pred = random_model.predict(test_X)

RandomForestClassifier()

In [47]:
random_y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [46]:
knn_model = KNeighborsClassifier()
knn_model.fit(train_X, train_y)
knn_y_pred = knn_model.predict(test_X)
knn_y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [48]:
lr_model = LogisticRegression()
lr_model.fit(train_X, train_y)
lr_y_pred = lr_model.predict(test_X)
lr_y_pred

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [49]:
pred = []
for i in range(len(random_y_pred)):
  vote_count = random_y_pred[i] + knn_y_pred[i] + lr_y_pred[i]
  if vote_count >= 2:
    pred.append(1)
  else:
    pred.append(0)

In [51]:
res_df = pd.DataFrame({'id': range(len(pred)), 'label': pred})

In [53]:
res_df.to_csv('/content/drive/MyDrive/5001_kaggle/pred.csv', index = False)